[package]
name = "mytrace"
version = "0.1.0"
authors = ["cydry3 <ysaita09@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
